backend:
  name: git-gateway

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: 'revision-notes'
    label: 'Revision Notes'
    folder: 'content/revision-notes'
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Resource ID', name: 'resource-id', widget: 'string' }
      - { label: 'Content (MDX)', name: 'body', widget: 'markdown' }
