backend:
  name: git-gateway

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'posts'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
